### ISSUE TITLE
Allow json output format

### ISSUE THREAD

**Issue by tdiesler** [animo/siera-cli#164]
**Describe your new idea or enhancement**

Alice invites Faber like this ...

```
aries-cli -e Alice connection invite --auto-accept
|
50006444-55c6-4587-987c-2a935c1999b6
http://localhost:8030?c_i=eyJAdHlwZSI6ICJkaWQ6...elZzdFQiXX0=
```

which is an output format that cannot be consumed easily by subsequent commands. 

How about providing a switch for json output, like this ...

```
aries-cli -e Alice -o json connection invite --auto-accept
{
   "connection_id": "50006444-55c6-4587-987c-2a935c1999b6",
   "url": "http://localhost:8030?c_i=eyJAdHlwZSI6ICJkaWQ6...elZzdFQiXX0="
}
```
We could then use `jq` to extract various attributes from the output to pass on to other commands

**Comment by tdiesler** [comment]
Here a workaround using sed

```
url=$(aries-cli -e Alice connection invite --auto-accept | sed -n 2p)
aries-cli -e Faber connection receive --url ${url}
```

**Comment by blu3beri** [comment]
We did have the idea for the `quiet` to just show the url. But a json output would also de a great addition to that. Xargs would allow you to send it to the next command.
