### ISSUE TITLE
Unify json and normal logger

### ISSUE THREAD

**Issue by blu3beri** [animo/siera-cli#242]
We can unify the json and normal logger so we just have one logger call and we can log the values for the normal logger and log the entire json when we have the `--json` flag enabled,

```rust
log!({
  "connection_id": "abc-def",
  "invitation_url": "https://..."
})
```
```sh
# Without flag
abc-def
https://...

# With flag
{
  "connection_id": "abc-def",
  "invitation_url": "https://..."
}
```

**Comment by morrieinmaas** [comment]
alos see discussion [here](https://github.com/animo/siera/pull/240)
