### ISSUE TITLE
Automate credential-offer returns 400 schema already exists error.

### ISSUE THREAD

**Issue by janrtvld** [animo/siera-cli#245]
**Describe the bug**

When i run `siera automate credential-offer` and i scan the QR code i get the following error when the credential is being issued:

`[error] 400: Schema full-credential-offer-automation 1.0 already exists`

**To Reproduce**

1. Run `siera automate credential-offer`
2. Scan the QR code
3. Wait for the connection to be setup

**Expected behavior**

It should send me a credential.

**Siera version (run `siera --version`)**

0.1.0

**Desktop OS**
MacOS Ventura 13.1

**Verbose logs**

Run your command with the `-vvv` flag. See `siera --help` for guidance.

<details>
  <summary>Logs</summary>

  ```
~
➜ siera automate credential-offer
Scan the QR code to accept the invitation

<QRCODE>

================
Credential offer
================

Created invitation with connection id 84ab4ef5-f705-43ef-a873-41177fa165e8.

Use this URL:

https://didcomm.agent.community.animo.id?c_i=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9jb25uZWN0aW9ucy8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiNTJkNzU1MWMtMzBmNC00Njk1LWE2MDUtZTNhOGQ1MDMxZjY3IiwgImltYWdlVXJsIjogImh0dHBzOi8vaS5pbWd1ci5jb20vZzNhYmNDTy5wbmciLCAibGFiZWwiOiAiQW5pbW8gQ29tbXVuaXR5IEFnZW50IiwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwczovL2RpZGNvbW0uYWdlbnQuY29tbXVuaXR5LmFuaW1vLmlkIiwgInJlY2lwaWVudEtleXMiOiBbIjZyaUdjNXRSdE5HbUdxek1QU1lSdkxLYXVVMXg2b0pncVF1ZFdlaWZ4VHZFIl19


Waiting for the invitation to be accepted. Timeout is 60 seconds...
Invitation accepted!
Fetching the connection...
[error] 400: Schema full-credential-offer-automation 1.0 already exists

  ```

</details>
<br/>

**Screenshots, screen recordings**
![image](https://user-images.githubusercontent.com/60812202/219587793-91e40498-69b5-404b-b3ee-1ea7eb898b82.png)

**Additional context**

**Comment by TimoGlastra** [comment]
The CLI is kinda broken currently. How much work is it to fix this? Can we check whether the schema exists and only create it if it doesn't exist yet?

**Comment by morrieinmaas** [comment]
Yes that should be possible and a good approach
